---
- name: data-to-s3
  hosts: '{{ target }}'
  become: True
  become_user: root

  tasks:
    - name: temporary spool directory
      file:
        path: "{{ local_path }}"
        state: directory
        mode: '0750'
        owner: "{{ data_user }}"

    - name: required package(s)
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - coreutils
          - curl

    - name: data-to-s3 shell script
      template:
        src: data-to-s3
        dest: /usr/local/bin/data-to-s3
        owner: "{{ data_user }}"
        mode: '0550'

    - name: user cron to fetch and push to s3
      cron:
        name: "data-to-s3"
        state: present
        user: "{{ data_user }}"
        minute: "*/10"
        state: present
        job: /usr/local/bin/data-to-s3
